version: "3"

# We define two services, meaning that we will have two running containers
services:
  # The first one is our flask container
  flask:
  # Build the Dockerfile inside the flask folder
    build: ./flask
    # and give this container the name flask
    container_name: flask
    # If something bad happens, restart the container
    restart: always
    # We will need to expose port 8080 as uwsgi is listening on this prot
    expose:
      - 8080
  
  # This is the container running the nginx web
  nginx:
    # Build the Dockerfile inside the nginx folder
    build: ./nginx
    # and give this container the name nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"